### ISSUE TITLE
Utilisation du "précédent" de navigateur

### ISSUE THREAD

**Issue by LoicTouzard** [EstLx/estlx.github.io#2]
Il y a un soucis avec l'utilisattion de "précédent" du navigateur.
Démarche : 
1. Je vais sur la page d'accueil
2. Sur cette meme page et je clique "Portfolio" (marche aussi pour Rearth mission 6, Kitchap) j'arrive sur la page du projet.
3. Si je fais précédente je tombe sur une page blanche

"Précédent" fonctionne correctement pour les projets GFaim ou design work.

**Comment by LoicTouzard** [comment]
J'ai pas trop de piste pour savoir d'où ça vient, peut être un probleme javascript de manipulation d'historique ?

**Comment by EstLx** [comment]
C'est en prod. Merci @LoicTouzard pour ce signalement.
