### ISSUE TITLE
image de "Portfolio"

### ISSUE THREAD

**Issue by LoicTouzard** [EstLx/estlx.github.io#3]
En format mobile l'image du premier projet "portfolio" sur la page d'accueil est beaucoup trop grand par rapport aux autres.
[capture d'ecran](http://puu.sh/xK5rc/e6b50d7a17.jpg)
C'est peut être le cas pour d'autres images sur le site.

**Comment by LoicTouzard** [comment]
Tu peux tenter un correctif en rajoutant a le css : 
```css
.image{
  max-height: 450px;
  overflow: hidden;
}
```

[demo](http://puu.sh/xK5KK/e8a06b2cf3.jpg)

Il faut vérifier ce que ça impacte sur les autres pages. Sinon mets un `id` sur l'element `<figure>` qui entoure le portfolio et affecte ce css à l'id en question

**Comment by EstLx** [comment]
C'est fait
